# Generated by Django 5.0.6 on 2025-11-12 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='utilisation_par_utilisateur',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre d'utilisations par utilisateur (0 pour illimité)"),
        ),
        migrations.AddField(
            model_name='promotionbanner',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='utilisation_max',
            field=models.PositiveIntegerField(default=1, help_text="Nombre maximal d'utilisations totales"),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='utilisations_effectuees',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='UsedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_utilisation', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Utilisé',
                'verbose_name_plural': 'Coupons Utilisés',
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
