# Generated by Django 5.0.6 on 2025-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_utilisation_par_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='utilisation_par_utilisateur',
        ),
        migrations.RemoveField(
            model_name='promotionbanner',
            name='actif',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='utilisation_max',
            field=models.PositiveIntegerField(default=1, help_text="Nombre maximal d'utilisations"),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='utilisations_effectuees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UsedCoupon',
        ),
    ]
