# Generated by Django 5.0.6 on 2025-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OptionPersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='photobooth',
            name='accessoires',
            field=models.ManyToManyField(blank=True, related_name='photobooths', to='photobooths.accessoire'),
        ),
        migrations.AddField(
            model_name='photobooth',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='photobooths', to='photobooths.optionpersonnalisee'),
        ),
    ]
