# Generated by Django 5.0.6 on 2025-08-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobooths', '0002_accessoire_optionpersonnalisee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photobooth',
            name='accessoires',
        ),
        migrations.RemoveField(
            model_name='photobooth',
            name='options',
        ),
        migrations.DeleteModel(
            name='Accessoire',
        ),
        migrations.DeleteModel(
            name='OptionPersonnalisee',
        ),
    ]
