# Generated by Django 5.0.6 on 2025-08-23 20:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('photobooths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Montant total de la facture (incluant les réductions).', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('failed', 'Échec du paiement'), ('refunded', 'Remboursée'), ('cancelled', "Annulée par l'utilisateur")], default='pending', max_length=50)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='ID de la session Stripe Checkout.', max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID du Payment Intent Stripe après succès.', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant de la réduction appliquée.', max_digits=10)),
                ('coupon_used', models.ForeignKey(blank=True, help_text='Coupon appliqué à cette facture.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_location', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('canceled', 'Annulée')], default='pending', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=2)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_linked', to='reservations.invoice')),
                ('photobooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photobooths.photobooth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
