# Generated by Django 5.0.6 on 2025-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_address',
            field=models.TextField(default=' 123 Rue des Lumières, 6000 Charleroi, Belgique', help_text='Adresse complète de la société'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_email',
            field=models.EmailField(default='bpgloire@gmail.com', help_text='Adresse email de la société', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_name',
            field=models.CharField(default='Idealbooth SARL', help_text='Nom de la société', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_phone',
            field=models.CharField(default='+32 465 45 67 89', help_text='Numéro de téléphone de la société', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_vat_number',
            field=models.CharField(default='N TVA 12345678900978', help_text='Numéro de TVA intracommunautaire', max_length=50),
            preserve_default=False,
        ),
    ]
