# Generated by Django 5.0.6 on 2025-08-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_invoice_company_address_invoice_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company_address',
            field=models.TextField(blank=True, help_text='Adresse complète de la société', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Adresse email de la société', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nom de la société', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_phone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone de la société', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_vat_number',
            field=models.CharField(blank=True, help_text='Numéro de TVA intracommunautaire', max_length=50, null=True),
        ),
    ]
