# Generated by Django 5.0.6 on 2025-11-12 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0003_remove_coupon_utilisation_par_utilisateur_and_more'),
        ('photobooths', '0003_remove_photobooth_accessoires_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('type_evenement', models.CharField(choices=[('mariage', 'Mariage'), ('bapteme', 'Baptême'), ('anniversaire', 'Anniversaire'), ('entreprise', 'Événement d’entreprise')], default='mariage', max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('photobooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photobooths.photobooth')),
            ],
        ),
    ]
